fin='~dmenemen/NA/MITgcm/run/STDOUT.0000';
EXPR={'time_secondsf', ...
      'dynstat_eta_max','dynstat_eta_min','dynstat_eta_mean', ...
      'dynstat_eta_sd','dynstat_eta_del2', ...
      'dynstat_uvel_max','dynstat_uvel_min','dynstat_uvel_mean', ...
      'dynstat_uvel_sd','dynstat_uvel_del2', ...
      'dynstat_vvel_max','dynstat_vvel_min','dynstat_vvel_mean', ...
      'dynstat_vvel_sd','dynstat_vvel_del2', ...
      'dynstat_wvel_max','dynstat_wvel_min','dynstat_wvel_mean', ...
      'dynstat_wvel_sd','dynstat_wvel_del2', ...
      'dynstat_theta_max','dynstat_theta_min','dynstat_theta_mean', ...
      'dynstat_theta_sd','dynstat_theta_del2', ...
      'dynstat_salt_max','dynstat_salt_min','dynstat_salt_mean', ...
      'dynstat_salt_sd','dynstat_salt_del2', ...
      'dynstat_sst_max','dynstat_sst_min','dynstat_sst_mean', ...
      'dynstat_sst_sd','dynstat_sst_del2', ...
      'dynstat_sss_max','dynstat_sss_min','dynstat_sss_mean', ...
      'dynstat_sss_sd','dynstat_sss_del2', ...
      'advcfl_vvel_max','advcfl_wvel_max','advcfl_W_hf_max', ...
      'advcfl_uvel_max', ...      
      'ke_max','ke_mean','ke_vol', ...
      'vort_r_min','vort_r_max','vort_a_mean', ...
      'vort_a_sd','vort_p_mean','vort_p_sd'};
CMD='vals=mitgcmhistory(fin';
for i=1:length(EXPR);
    CMD=[CMD ',''' EXPR{i} ''''];
end
CMD=[CMD ');'];
eval(CMD)

fld=[1 6 11 16 21 26 31 36 41 45 48 54];
for i=2:length(fld)
    clf reset, orient tall, wysiwyg
    for v=(fld(i-1)+1):fld(i)
        subplot(fld(i)-fld(i-1),1,v-fld(i-1))
        plot(vals(:,1)/86400,vals(:,v));
        title(EXPR{v},'interpreter','none')
    end
    xlabel('day')
    eval(['print -djpeg ' EXPR{v}])
end
